config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :users do
    get :favorites, on: :collection
  end
  resources :photos do
    resource :favorites, only: [:create, :destroy ]
  end
  resources :sessions, only: [:new, :create, :destroy ]
  resources :favorites, only: [:create, :destroy ]

  mount LetterOpenerWeb::Engine, at: "/letter_oppener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  validates_uniqueness_of :photo_id, scope: :user_id
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :text, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation { email.downcase! }

  has_secure_password
  validates :password, length: { minimum: 6 }, on: :new 

  mount_uploader :image, ImageUploader

  has_many :photos
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_photo

  def create
    @favorite = Favorite.create(user_id: current_user.id, photo_id: @photo.id )
    redirect_to photo_path(@photo.id), notice: "「いいね」をしました"
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, photo_id: @photo.id )
    @favorite.destroy
    redirect_to photo_path(@photo.id), notice: "「いいね」を解除しました"
  end

  private
  def set_photo
    @photo = Photo.find(params[:photo_id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.build(photo_params)
    if @photo.save
      PostMailer.post_mail(@photo).deliver
      redirect_to photos_path, notice: "登録しました"
    else
      render :new, notice: "登録エラーです"
    end
  end

  def index
    @photos = Photo.all
  end

  def show
  end

  def edit
    redirect_to photo_path(@photo.id) unless current_user.id == @photo.user.id
  end

  def update
    if current_user.id == @photo.user.id
      if @photo.update
        redirect_to photos_path, notice: "編集しました"
      else
        render :edit, notice: "編集エラーです"
      end
    else
      redirect_to photos_path
    end
  end

  def destroy
    @photo.destroy
    redirect_to photos_path, notice: "投稿を削除しました"
  end

  private
  def photo_params
    params.require(:photo).permit(:image, :text, :image_cache )
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create ]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  skip_before_action :login_required, only: [:new, :create ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice: "登録しました"
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
  end

  def favorites
    @user = User.find(current_user.id)
    @photos = @user.photos

    favorites = Favorite.where(user_id: current_user.id).pluck(:photo_id)
    @favorite_list = Photo.find(favorites)
  end

  def edit
    redirect_to user_path(@user.id) unless current_user.id == @user.id
  end

  def update
    if current_user.id == @user.id
      if @user.update(user_params)
        redirect_to user_path(@user.id), notice: "画像を変更しました"
      else
        redirect_to user_path(@user.id)
      end
    else
      redirect_to  user_path(@user.id)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app-title navbar navbar-expand-md navbar-light bg-light">
      <div class="navbar-brand">photos</div>
    </div>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <%= link_to "一覧", photos_path %>
      <%= link_to "お気に入り", favorites_users_path(current_user.id) %>
    <% else %>
      <%= link_to "Sign up",new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <% flash.each do |key,value| %>
      <%= content_tag(:div,value, class:"#{key}") %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: @photo, local: true) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= @photo.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-4">
    <%= f.label :image %>
    <%= image_tag(@photo.image.url) if @photo.image && @photo.image.url %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group mt-4">
    <%= f.label :text %>
    <%= f.text_area :text , class: "form-control" %>
  </div>

  <%= f.submit "登録", class: "btn btn-primary mt-4" %>
<% end %>

app/views/photos/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

app/views/photos/index.html.erb
<h1>一覧</h1>

<div class="mb-3">
  <table class="table table-hover">
    <tr>
      <th>写真</th>
      <th>テキスト</th>
      <th>投稿者</th>
      <th></th>
    </tr>
    <% @photos.each do |p| %>
    <tr>
      <th><%= link_to image_tag(p.image.url), photo_path(p.id) %></th>
      <th><%= link_to p.text, photo_path(p.id) %></th>
      <th><%= p.user.name %></th>
      <% if current_user.id == p.user.id %>
        <th><%= link_to "編集", edit_photo_path(p.id), class: "btn btn-secondary" %>
        <%= link_to "削除", photo_path(p.id), method: :delete ,data: { confirm: '本当に削除していいですか'}, class: "btn btn-danger mx-2" %></th>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>
<%= link_to "新規登録", new_photo_path , class: "btn btn-primary" %>

app/views/photos/new.html.erb
<h1>新規投稿</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<h1>詳細確認</h1>

<table class="table table-hover">
  <tbody>
    <tr>
      <th>画像</th>
      <td><%= image_tag(@photo.image.url) %>
    </tr>
    <tr>
      <th>テキスト</th>
      <td><%= @photo.text %>
    </tr>
    <tr>
      <th>投稿日時</th>
      <td><%= @photo.created_at %>
    </tr>
    <tr>
      <th>更新日時</th>
      <td><%= @photo.updated_at %>
    </tr>
    <tr>
      <th>投稿者</th>
      <td><%= @photo.user.name %>
    </tr>
  </tbody>
</table>
<% if !Favorite.exists?(user: current_user, photo_id: @photo.id) %>
  <%= link_to "いいね",photo_favorites_path(@photo), method: :post, class: "btn btn-primary" %>
<% else %>
  <%= link_to "いいね解除",photo_favorites_path(@photo), method: :delete, class: "btn btn-danger" %>
<% end %>

<% if current_user.id == @photo.user.id %>
  <%= link_to "編集", edit_photo_path(@photo.id), class: "btn btn-secondary" %>
  <%= link_to "削除", photo_path(@photo.id), method: :delete ,data: { confirm: '本当に削除していいですか'}, class: "btn btn-danger mx-3" %>
<% end %>

app/views/users/edit.html.erb
<h1>画像の登録</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="field">
    <%= f.label :image %>
    <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
    <%= f.file_field :image , class: "mt-5"%>
    <%= f.hidden_field :image_cache %>
    <div class="mt-4">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="mt-4">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "登録", class: "btn btn-primary mt-4" %>
  </div>
  <%= link_to "戻る", user_path(@user.id), class: "btn btn-secondary mt-4" %>
<% end %>

app/views/users/favorites.html.erb
<h1>お気に入り一覧</h2>

<% if @favorite_list.present? %>
  <table>
    <tr>
      <td>画像</td>
      <td>テキスト</td>
    </tr>
    <% @favorite_list.each do |p| %>
    <tr>
      <tH><%= image_tag(p.image.url) %></th>
      <th><%= p.text %></th>
    <% end %>
  </table>
<% else %>
  <p>お気に入り一覧はありません</p>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<div class="mb-3">
  <table class="table table-hover">
    <tr>
      <th>ユーザーID</th>
      <th>ユーザー名</th>
    </tr>
    <% @users.each do |u| %>
    <tr>
      <th><%= link_to u.id, user_path(u.id) %></th>
      <th><%= link_to u.name, user_path(u.id) %></th>
    </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<h1>新規登録</h1>

<% if @user.errors.any? %>
  <div id="error_expanation">
    <h2><%= pluralize(@user.errors.count,"error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group mt-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group mt-3">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group mt-3">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group mt-3">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <%= f.submit "登録", class: "btn btn-primary mt-4" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p><%= image_tag(@user.image.url) if @user.image && @user.image.url %></p>

<% if current_user.id == @user.id %>
  <%= link_to "画像の登録と編集", edit_user_path, class: "btn btn-primary" %>
<% end %>
<p>メールアドレス：　<%= @user.email %></p>